apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica
  labels:
    app_name: application
    tier: frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: echo
        image: registry.cluster.wik.cloud/public/echo